spring:
  application:
    name: meetmate-backend
  profiles:
    default: local
  jackson:
    time-zone: Asia/Seoul

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
